#!/usr/bin/env python3
# Generates adapters.inc from maps.json: for each new interface version the
# game's OpenVR plugin asks for (OpenVR SDK 2.12.14) and an older one that
# OpenComposite implements, which old slot each new slot calls (-1: a method
# the old version lacks; the shim answers it itself). maps.json was made by
# comparing the method lists of openvr.h 2.12.14 with OpenComposite's own
# OpenVR headers (2.5.1, 1.23.7): only methods were added, none changed.
import json,os
here=os.path.dirname(os.path.abspath(__file__))
maps=json.load(open(os.path.join(here,'maps.json')))
out=['/* generated by gen.py from maps.json - do not edit */']
for key,m in sorted(maps.items()):
    name=key.replace('IVR','').upper()
    out.append('static const short MAP_%s[%d]={%s};'%(name,len(m['map']),','.join(str(x) for x in m['map'])))
    out.append('#define OLD_COUNT_%s %d'%(name,len(m['old'])))
    for i,v in enumerate(m['map']):
        if v<0: out.append('#define NEW_%s_%s %d'%(name,m['new'][i].upper(),i))
    if 'PollNextEventWithPose' in m['old']:
        out.append('#define OLD_%s_POLLNEXTEVENTWITHPOSE %d'%(name,m['old'].index('PollNextEventWithPose')))
# 0.1.178: OpenComposite answers some methods by stopping the game ("Hit
# stubbed file"); in an adapted interface these few answer "nothing" instead
# (kind 0: 0/false/no-op, 1: 0.0f, 2: error 1 (RequestFailed), 3: "").
OVERRIDES={
 'SYSTEM':[('GetEventTypeNameFromEnum',3),('GetD3D9AdapterIndex',0),('GetAppContainerFilePaths',0)],
 'COMPOSITOR':[('GetFrameTimeRemaining',1),('GetCumulativeStats',0),('CompositorGoToBack',0),('CompositorQuit',0),
  ('IsFullscreen',0),('GetCurrentSceneFocusProcess',0),('GetLastFrameRenderer',0),('ShowMirrorWindow',0),
  ('HideMirrorWindow',0),('IsMirrorWindowVisible',0),('CompositorDumpImages',0),('GetMirrorTextureGL',2),
  ('ReleaseSharedGLTexture',0),('LockGLSharedTextureForAccess',0),('UnlockGLSharedTextureForAccess',0),
  ('IsMotionSmoothingSupported',0),('IsMotionSmoothingEnabled',0),('GetPosesForFrame',2)],
 'OVERLAY':[('WaitFrameSync',0)],
}
for fam,items in sorted(OVERRIDES.items()):
    new_list=[m['new'] for k,m in sorted(maps.items()) if k.replace('IVR','').upper().startswith(fam+'_')][0]
    slots=[new_list.index(n) for n,_ in items]
    out.append('static const short OVR_%s_SLOT[%d]={%s};'%(fam,len(items),','.join(map(str,slots))))
    out.append('static const unsigned char OVR_%s_KIND[%d]={%s};'%(fam,len(items),','.join(str(k) for _,k in items)))
    out.append('#define OVR_%s_COUNT %d'%(fam,len(items)))
thunks=max(len(m['old']) for m in maps.values())
out.append('#define THUNKS %d'%thunks)
open(os.path.join(here,'adapters.inc'),'w').write('\n'.join(out)+'\n')
asm=['/* generated by gen.py - do not edit */','.text','.p2align 4','.globl shim_thunk_base','shim_thunk_base:']
for k in range(thunks):
    asm+=['.p2align 4','    movq 8(%rcx), %rcx','    movq (%rcx), %rax','    jmpq *%d(%%rax)'%(8*k)]
open(os.path.join(here,'thunks.S'),'w').write('\n'.join(asm)+'\n')
print('adapters.inc and thunks.S:',thunks,'thunks')
